name: First Workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome messsage
              run: echo "my first G/A"

            - name: List files
              run: ls
            - name: read file
              run: cat README.md